using System;

namespace Marge.Infrastructure
{
    /// <summary>
    /// Mark simples classes as events generated by commands
    /// </summary>
    public interface IEvent { }

    public struct EventWrapper 
    {
        public Guid StreamId { get; }
        public IEvent Event { get; }

        public EventWrapper(Guid streamId, IEvent @event)
        {
            StreamId = streamId;
            Event = @event;
        }
    }
}
